# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-14 21:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'New Planet', max_length=256, null=True)),
                ('roman_number', models.CharField(default=b'I', max_length=16, null=True)),
                ('neutral_gold', models.BooleanField(default=False)),
                ('neutral_emeril', models.BooleanField(default=False)),
                ('neutral_nickel', models.BooleanField(default=False)),
                ('neutral_aluminium', models.BooleanField(default=False)),
                ('neutral_copper', models.BooleanField(default=False)),
                ('neutral_iridium', models.BooleanField(default=False)),
                ('silicate_chrysonite', models.BooleanField(default=False)),
                ('exotic_calium', models.BooleanField(default=False)),
                ('exotic_omegon', models.BooleanField(default=False)),
                ('exotic_radnox', models.BooleanField(default=False)),
                ('exotic_murrine', models.BooleanField(default=False)),
                ('trade_gravitino', models.BooleanField(default=False)),
                ('trade_albumen', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'nms_planet',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'nms_player',
            },
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'New System', max_length=256, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nms.Player')),
            ],
            options={
                'db_table': 'nms_system',
            },
        ),
        migrations.AddField(
            model_name='planet',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nms.System'),
        ),
    ]
