# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-21 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nms', '0002_createsuperuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='planet',
            name='trade_sac_venom',
            field=models.BooleanField(default=False),
        ),
    ]
